spring:
  devtools:
    livereload:
      enabled: true
  config:
    import: optional::file.env[.properties]
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog
      username: admin
      password: password
      authentication-database: admin
      auto-index-creation: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tech_blog
#    username: root
#    password: secret
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

selflearntech:
  trace: true
